export function Privacy() {
  return (
    <>
      <section className="page-hero"><div className="container">
        <span className="eyebrow">Privacidade e proteção de dados</span>
        <h1 className="title">Sua privacidade importa.</h1>
        <p className="lead">Entenda o formulário, os serviços externos e suas escolhas neste site.</p>
        <p className="kicker">Atualizado em 6 de outubro de 2026 · Versão demonstrativa</p>
      </div></section>
      <section className="section--tight"><div className="container stack" style={{ maxWidth: 850 }}>
        <article className="card"><h2>1. Quem é responsável</h2><p>Este site apresenta uma demonstração da Clínica Sorriso. A identificação jurídica da clínica, o responsável pelo tratamento de dados e o canal para solicitações de privacidade ainda precisam ser confirmados. Os contatos demonstrativos não devem ser utilizados para enviar dados pessoais reais.</p><p>O crédito de desenvolvimento da SoeiroTech não identifica, por si só, o controlador dos dados da clínica.</p></article>
        <article className="card"><h2>2. Formulário de contato</h2><p>Nome e telefone são solicitados para preparar uma conversa sobre atendimento. Interesse, período e mensagem são opcionais. Os campos ficam na memória desta página; esta versão não possui uma API para recebê-los nem grava esses campos em um banco de dados ou no armazenamento local do site.</p><p>Ao continuar no WhatsApp, os campos entram em uma mensagem na URL enviada ao serviço externo. Essa URL pode aparecer no histórico do navegador. A clínica recebe a mensagem quando você a envia no WhatsApp. Você pode revisar, editar ou desistir antes do envio.</p><p>Não informe diagnóstico, exames, documentos, dados de saúde ou outras informações sensíveis. Durante a demonstração, use apenas dados fictícios.</p></article>
        <article className="card"><h2>3. WhatsApp e outros serviços</h2><p>Os links de WhatsApp, mapas, Instagram e SoeiroTech levam a serviços externos, com regras próprias. A hospedagem na Cloudflare e as imagens externas podem envolver processamento de informações técnicas, como IP e dados da requisição, para entregar o conteúdo e proteger o serviço.</p><p>O roteiro “Minha primeira visita” permanece nesta página até que você abra seu link de WhatsApp; nesse momento a preferência integra a mensagem na URL. Não há envio automático à clínica.</p><p><a href="https://www.whatsapp.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">Privacidade do WhatsApp ↗</a> · <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener noreferrer">Privacidade da Cloudflare ↗</a></p></article>
        <article className="card"><h2>4. Cookies e armazenamento</h2><p>O código atual do site não instala cookies de publicidade ou ferramentas de análise de comportamento. Serviços externos e a infraestrutura de hospedagem podem ter recursos próprios. Caso novas ferramentas sejam adicionadas, este aviso e os controles de privacidade deverão ser revisados antes da ativação.</p></article>
        <article className="card"><h2>5. Finalidades e conservação</h2><p>A conversa solicitada por você tem a finalidade de esclarecer dúvidas e organizar atendimento. Esta página não define a base legal, os prazos de conservação ou as práticas internas da futura clínica. Essas informações precisam ser estabelecidas pelo responsável antes de receber dados reais, inclusive para mensagens e registros fora do site.</p></article>
        <article className="card"><h2>6. Seus direitos</h2><p>A LGPD prevê direitos como confirmação do tratamento, acesso, correção e, nas hipóteses aplicáveis, eliminação, portabilidade, informação sobre compartilhamento e revogação do consentimento. Solicitações devem ser dirigidas ao controlador pelo canal oficial, ainda pendente de confirmação nesta demonstração.</p><p><a href="https://www.gov.br/anpd/pt-br/assuntos/titular-de-dados-1/direito-dos-titulares" target="_blank" rel="noopener noreferrer">Conheça seus direitos na ANPD ↗</a></p></article>
        <article className="card"><h2>7. Antes do atendimento real</h2><p>Este aviso descreve o funcionamento da demonstração. Identificação do controlador, canal oficial, bases legais, fornecedores e prazos de conservação devem ser validados para a operação real. A presença desta página não certifica conformidade integral com a LGPD.</p></article>
      </div></section>
    </>
  )
}
